services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./datac:/data
      - ./configc:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 81:80
      - 445:443
    entrypoint: /usr/bin/caddy run --adapter caddyfile --config /config/Caddyfile

  headscale:
    container_name: headscale
    image: headscale/headscale:latest
    command: serve
    restart: unless-stopped
    ports:
      - 8080:8080
      - 9090:9090
    volumes:
      - ./config:/etc/headscale/
      - ./data:/var/lib/headscale/

  headscale-ui:
    container_name: headscale-ui
    image: ghcr.io/gurucomputing/headscale-ui:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - 9080:8080
      - 8443:8443  
